variables:
  KUBERNETES_CPU_REQUEST: 2000m
  KUBERNETES_CPU_LIMIT: 2000m
  KUBERNETES_MEMORY_REQUEST: 8Gi
  KUBERNETES_MEMORY_LIMIT: 8Gi

stages:
  - test
  - scan

go_test:
  stage: test
  image: cr.d.xiaomi.net/miflow/golang:1.20-centos7 # 对应build镜像
  script:
    - make fast-test
  artifacts:
    paths:
      - cover.out

sonar_scan:
  stage: scan
  dependencies:
    - go_test
  script:
    - fusion-cli sonar config --token $CI_SONAR_TOKEN
    - fusion-cli sonar scan --key=$CI_PROJECT_ID-$CI_PROJECT_NAME --ignore-quality-gate --sources . --report -- 
      -Dsonar.exclusions='**/vendor/**','**/*_test.go','**/build/**' 
      -Dsonar.test.exclusions='**/vendor/**','**/*_test.go' 
      -Dsonar.go.coverage.reportPaths='cover.out' 
      -Dsonar.branch.name=$CI_COMMIT_REF_NAME
      -Dsonar.verbose
